version: "3.7"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm-app
    networks:
      - alifacademy

  php-fpm-app:
    build:
      dockerfile: ./docker/php/php-fpm.Dockerfile
      context: .
    container_name: php-fpm-app
    working_dir: /app
    volumes:
      - ./:/app
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - alifacademy

  php-cli-app:
    build:
      dockerfile: ./docker/php/php-cli.Dockerfile
      context: .
    container_name: php-cli-app
    command: sleep infinity
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - alifacademy

  redis:
    image: redis:7.2.2-alpine
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    networks:
      - alifacademy

networks:
  alifacademy:
    name: "alifacademy"
    external: true
