# Используем лёгкий образ Python на базе Alpine
FROM python:3.10-alpine

# Копируем наш Python-скрипт в контейнер
COPY script.py /script.py

# Запускаем наш скрипт при запуске контейнера
CMD ["python", "/script.py"]